# ! Make Jenkins Persistent Volumes Root Directory

# Root Mount Path 생성
- name: "[ STEP 3 ] # 1-1. Make Root Mount Path"
  become: true
  shell: mkdir -p {{JENKINS_STORAGE_MOUNT_PATH}}

# Root Directory 확인
- name: "[ STEP 3 ] # 1-2. Check Target Root Directory Exist"
  stat:
    path: "{{JENKINS_STORAGE_MOUNT_PATH}}/jenkins-volume"
  register: stat_data_dir_result

# Jenkins-volume이 있으면 삭제
- name: "[ STEP 3 ] # 1-3. Delete Exist Root Directory"
  become: true
  shell: rm -rf "{{JENKINS_STORAGE_MOUNT_PATH}}/jenkins-volume"
  when: stat_data_dir_result.stat.exists

# Jenkins Volume 생성 (sample source 있는 경우)
- name: "[ STEP 3 ] # 2-1. Make Jenkins Data Directory"
  become: true
  file:
    path: "{{JENKINS_STORAGE_MOUNT_PATH}}/jenkins-volume"
    state: directory
  when: not JENKINS_SAMPLE_SOURCE

# Jenkins Volume 생성 (sample source 없는 경우)
- name: "[ STEP 3 ] # 2-1. Make Jenkins Data Directory"
  become: true
  unarchive:
    src: archives/helm/jenkins-volume.tar.gz
    dest: "{{JENKINS_STORAGE_MOUNT_PATH}}"
  when: JENKINS_SAMPLE_SOURCE

# Volume 접근권한 부여 
- name: "[ STEP 3 ] # 3. Grant Permission of Directory"
  become: true
  shell: |
    chown -R 1000 {{JENKINS_STORAGE_MOUNT_PATH}}/jenkins-volume
