- name: Remove k8s Resource
  hosts: control
  remote_user: "{{ USER }}"
  become: True
  gather_facts: True
  ignore_errors: True
  tasks:
  - name: Remove k8s Resource
    shell: |

- name: Uninstall rke2-cluster-workers
  hosts: workers
  remote_user: "{{ USER }}"
  become: True
  gather_facts: True
  ignore_errors: True
  tasks:
  - name: Uninstall RKE2 worker nodes
    shell: /usr/local/bin/rke2-uninstall.sh

- name: Uninstall rke2-cluster-masters-connect
  hosts: masters-connect
  remote_user: "{{ USER }}"
  become: True
  gather_facts: True
  ignore_errors: True
  tasks:
  - name: Uninstall RKE2 master nodes
    shell: /usr/local/bin/rke2-uninstall.sh

- name: Uninstall rke2-cluster-masters-init
  hosts: master-init
  remote_user: "{{ USER }}"
  become: True
  gather_facts: True
  ignore_errors: True
  tasks:
  - name: Uninstall RKE2 master nodes
    shell: /usr/local/bin/rke2-uninstall.sh

#

