---
- name: 8.19.1. Add Helm repository
  ansible.builtin.shell:
    cmd: "/usr/local/bin/helm repo add cnstudio {{ HELM_REPO_URL }} --username admin --password admin1234"
  ignore_errors: yes
  
- name: 8.19.2. Update Helm repositories
  ansible.builtin.shell:
    cmd: "/usr/local/bin/helm repo update"

- name: 8.19.3. Install kafka
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/helm install kafka \
      --namespace kafka cnstudio/kafka --version {{ KAFKA_VERSION }} \
      --create-namespace \
      --set nodeSelector.db=true \
      --set controller.replicaCount=1
