- name: 8.1.1. Add Helm repository
  ansible.builtin.shell:
    cmd: "/usr/local/bin/helm repo add cnstudio {{ HELM_REPO_URL }} --username admin --password admin12341234 --insecure-skip-tls-verify"
  tags:
    - catalog_rancherui

- name: 8.1.2. Deploy rancher helm chart
  ansible.builtin.shell:
    cmd: |
      helm install rancher cnstudio/rancher \
      --namespace cattle-system --create-namespace \
      --set bootstrapPassword="admin" \
      --set tls=external \
      --set ingress.enabled=true \
      --set hostname=rancher.cnstudio.kt.com 
  tags:
    - catalog_rancherui

- name: 8.1.3. Wait for Rancher to be ready
  ansible.builtin.shell:
    cmd: |
      kubectl rollout status deployment rancher -n cattle-system
  register: rancher_status
  until: rancher_status.rc == 0
  retries: 30
  delay: 10
  tags:
    - catalog_rancherui

