#########  프로젝트 #########
PROJECT_NAME: 카탈로그 시언 v0.1
PROJECT_GROUP_NAME: KT
BRANCH_NAME: kt-01
USER: admin

###############버전 정보 확인 ############
LONGHORN_VERSION: 1.6.1
PROMETHEUS_VERSION: 56.8.2
OPENSEARCH_VERSION: 2.21.0
JAEGER_VERSION: 3.1.2
ISTIO_VERSION: 1.22.2
ARGOCD_VERSION: 7.0.0
MINIO_VERSION: 2024.07.04
VELERO_VERSION: 1.13.1
KEYCLOAK_VERSION: 19.0.0
RANCHERUI_VERSION: 2.8.5
GITLAB_VERSION: 7.11.2
JENKINS_VERSION:  5.4.3
NEUVECTOR_VERSION: 2.7.7
MARIADB_VERSION: 18.0.2
MYSQL_VERSION: 10.2.2
POSTGRESQL_VERSION: 14.2.7
KAFKA_VERSION: 29.3.4
REDIS_VERSION: 10.2.5

############### 설치 여부 확인 #############
DEPLOY_LONGHORN: true
DEPLOY_PROMETHEUS: true
DEPLOY_OPENSEARCH: true
DEPLOY_JAEGER: true
DEPLOY_ISTIO: true
DEPLOY_ARGOCD: true
DEPLOY_MINIO: true
DEPLOY_VELERO: true
DEPLOY_KEYCLOAK: true
DEPLOY_NODEJSCODE: true
DEPLOY_APIGATEWAY: true
DEPLOY_NODEJS: true
DEPLOY_JAVACODE: true
DEPLOY_PYTHONCODE: true
DEPLOY_RANCHERUI: true
DEPLOY_GITLAB: true
DEPLOY_GITLAB_RUNNER: false
DEPLOY_JENKINS: true
DEPLOY_NEUVECTOR: true
DEPLOY_MARIADB: true
DEPLOY_MYSQL: true
DEPLOY_POSTGRESQL: true
DEPLOY_KAFKA: true
DEPLOY_REDIS: true
#
########## 카탈로그 Helm Chart 버전 정보 #########
#LONGHORN_VERSION: 1.6.1
#JENKINS_VERSION: 5.4.3
#GITLAB_VERSION: 7.11.2
#JAVACODE_VERSION: 
#MYSQL_VERSION: 10.2.2
#POSTGRESQL_VERSION: 15.2.9
#REDIS_VERSION: 10.2.5
#NEUVECTOR_VERSION: 2.7.7
#ISTIO_VERSION: 1.22.2 
#OPENSEARCH_VERSION: 2.21.0
#
########## 카탈로그 설치 여부 정보 #########
#DEPLOY_LONGHORN: true
#DEPLOY_JENKINS: true
#DEPLOY_GITLAB: true
#DEPLOY_JAVACODE: true
#DEPLOY_POSTGRESQL: true
#DEPLOY_REDIS: true
#DEPLOY_NEUVECTOR: true
#DEPLOY_ISTIO: true
#DEPLOY_OPENSEARCH: true
#DEPLOY_GITLAB_RUNNER: false
#
######### 노드 연결 정보 #########
CONTROL_NODE_NAME: controller-node
MASTER_NODE_NAME: master-node01, master-node02, master-node03
WORKER_NODE_NAME: worker-node01, worker-node02, worker-node03, worker-node04, storage-node01, storage-node02, storage-node03, db-node01, db-node02
CONTROL_NODE_IP: 10.71.163.68
MASTER_NODE_IP: 10.71.163.70, 10.71.163.79, 10.71.163.87
WORKER_NODE_IP: 10.71.163.80, 10.71.163.81, 10.71.163.74, 10.71.163.83, 10.71.163.77, 10.71.163.78, 10.71.163.92, 10.71.163.94, 10.71.163.84

######### ALL Servers 정보 #########
ALL_Servers:
  - name: rke2-control-node01
    ip: 10.71.163.68
    roles:
      - control
    labels:
      - control=true
  - name: rke2-master-node01
    ip: 10.71.163.70
    roles:
      - control-plane
    labels:
      - master=true
  - name: rke2-master-node02
    ip: 10.71.163.79
    roles:
      - control-plane
    labels:
      - master=true
  - name: rke2-master-node03
    ip: 10.71.163.87
    roles:
      - control-plane
    labels:
      - master=true
  - name: rke2-worker-node01
    ip: 10.71.163.80
    roles:
      - worker
    labels:
      - worker=true
      - route=true
  - name: rke2-worker-node02
    ip: 10.71.163.81
    roles:
      - worker
    labels:
      - worker=true
      - route=true
  - name: rke2-worker-node03
    ip: 10.71.163.74
    roles:
      - worker
    labels:
      - worker=true
  - name: rke2-worker-node04
    ip: 10.71.163.83
    roles:
      - worker
    labels:
      - worker=true
  - name: rke2-worker-node05
    ip: 10.71.163.77
    roles:
      - worker
    labels:
      - worker=true
      - storage=true
      - "node.longhorn.io/create-default-disk=true"
  - name: rke2-worker-node06
    ip: 10.71.163.78
    roles:
      - worker
    labels:
      - worker=true
      - storage=true
      - "node.longhorn.io/create-default-disk=true"
  - name: rke2-worker-node07
    ip: 10.71.163.92
    roles:
      - worker
    labels:
      - worker=true
      - storage=true
      - "node.longhorn.io/create-default-disk=true"
  - name: rke2-worker-node08
    ip: 10.71.163.94
    roles:
      - worker
    labels:
      - worker=true
      - db=true
  - name: rke2-worker-node09
    ip: 10.71.163.84
    roles:
      - worker
    labels:
      - worker=true
      - db=true




######## Labels ############
labels:
  nodes:
    - name: "rke2-master-node01"
      labels:
        - "master=true"
    - name: "rke2-master-node02"
      labels:
        - "master=true"
    - name: "rke2-master-node03"
      labels:
        - "master=true"
    - name: "rke2-worker-node01"
      labels:
        - "worker=true"
        - "route=true"
    - name: "rke2-worker-node02"
      labels:
        - "worker=true"
        - "route=true"
    - name: "rke2-worker-node03"
      labels:
        - "worker=true"
    - name: "rke2-worker-node04"
      labels:
        - "worker=true"
    - name: "rke2-worker-node05"
      labels:
        - "worker=true"
        - "storage=true"
        - "node.longhorn.io/create-default-disk=true"
    - name: "rke2-worker-node06"
      labels:
        - "worker=true"
        - "storage=true"
        - "node.longhorn.io/create-default-disk=true"
    - name: "rke2-worker-node07"
      labels:
        - "worker=ture"
        - "storage=true"
        - "node.longhorn.io/create-default-disk=true"
    - name: "rke2-worker-node08"
      labels:
        - "worker=true"
        - "db=true"
    - name: "rke2-worker-node09"
      labels:
        - "worker=true"
        - "db=true"

######### Taints ############
taints:
  nodes:
    - name: "rke2-master-node01"
      taints:
        - "master=true:NoSchedule"
    - name: "rke2-master-node02"
      taints:
        - "master=true:NoSchedule"
    - name: "rke2-master-node03"
      taints:
        - "master=true:NoSchedule"
  
