# Configure kernel params
- name: 6.1. Copy Kernel Params
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf

- name: 6.2. Apply Kernel Params
  shell: |
    sysctl -p /etc/sysctl.conf

## Install_configure_rke2
- name: 6.3. Uninstall RKE2
  shell: rke2-uninstall.sh
  ignore_errors: True

- name: 6.4. Install and set RKE2
  shell: INSTALL_RKE2_TYPE=agent INSTALL_RKE2_ARTIFACT_PATH="{{ playbook_dir }}/../packages/rancher" INSTALL_RKE2_SYSTEM_DEFAULT_REGISTRY="{{ REGISTRY_URL }}{{ ':' }}5000" sh {{ playbook_dir }}/../packages/rancher/install.sh

## Configure Private registry
- name: 6.5. Create directories(Docker, RKE2, containerd)
  file:
    path: "{{ item.DIR }}"
    state: directory
  with_items: "{{ REGISTRY_CONFIG }}"

- name: 6.6. Set private repo for (Docker, RKE2, containerd)
  copy:
    dest: "{{ item.DIR }}/{{ item.FILE }}"
    content: "{{ item.CONTENT }}"
  with_items: "{{ REGISTRY_CONFIG }}"

## RKE2 configuration file
- name: 6.7. Make necessary directories
  file:
    path: /etc/rancher/rke2
    state: directory

- name: 6.8. Copy token
  copy:
    src: "{{ playbook_dir }}/../node-token/token"
    dest: /root/node-token

- name: 6.9. Display the cluster token from the file and emphasize it
  shell: cat /root/node-token
  register: node_token

- name: 6.10. Display the cluster token from the file and emphasize it
  shell: cat /root/node-token
  register: node_token

- name: 6.11. Add the content to the file
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      server: https://{{ ALL_Servers[0].ip }}:9345
      token: {{ node_token.stdout }} #TODO: 클러스터 토큰값 고정
      node-name: {{ inventory_hostname }}

## RKE2 Start
- name: 6.12. Enable and start the rke2-agent service
  systemd_service:
    name: rke2-agent
    state: started
    enabled: true
  register: "check_rke2angent_state"

- name: 6.13. Print rke2-agent service status
  debug:
    msg: "{{ check_rke2angent_state }}"
