## Create kubeconfig directory
- name: 4.1. Create directory
  file:
    path: "{{ item  }}"
    state: directory
  with_items:
    - $HOME/.kube
    - "/home/{{ USER }}/.kube"

## Copy kubeconfig file
- name: 4.2. Copy kubeconfig file
  copy:
    src: "{{ playbook_dir }}/../kubeconfig"
    dest: "{{ item  }}"
  with_items:
    - $HOME/.kube/config
    - "/home/{{ USER }}/.kube/config"

## Copy kubectl file
- name: 4.3. Copy kubectl file
  shell: sudo cp {{ playbook_dir }}/..//kubectl /usr/bin/kubectl

- name: 4.4. Chmod
  shell: sudo chmod 775 /usr/bin/kubectl

## Extract k9s, helm
- name: 4.5. Create directory for temp 
  file:
    path: "{{ playbook_dir }}/../packages/{{ item.DIR }}/tmp"
    state: directory
  with_items:
    - { DIR: 'tools' }
- name: 4.6. Extract k9s, helm
  unarchive:
    src: "{{ playbook_dir }}/../packages/{{ item.DIR }}/{{ item.FILE_NAME }}"
    dest: "{{ playbook_dir }}/../packages/{{ item.DIR }}/tmp"
    remote_src: yes
  with_items:
    - { DIR: 'tools', FILE_NAME: 'helm-v3.15.1-linux-amd64.tar.gz' }
    - { DIR: 'tools', FILE_NAME: 'k9s_Linux_amd64.tar.gz' }

##  Copy files for k9s
- name: 4.7. Copy file for k9s
  shell: sudo cp {{ playbook_dir }}/../packages/tools/tmp/k9s /usr/local/bin

## Copy file for helm
- name: 4.8. Copy file for helm
  shell: sudo cp {{ playbook_dir }}/../packages/tools/tmp/linux-amd64/helm /usr/local/bin

##  Copy files for yq
- name: 4.9. Copy file for yq
  shell: sudo cp {{ playbook_dir }}/../packages/tools/yq /usr/local/bin